// =============================================================================
//                     THREAD MODEL - MongoDB Schema
// =============================================================================
/**
 * 📚 WHAT IS THIS FILE?
 * ---------------------
 * Defines the MongoDB schema for chat threads using Mongoose.
 * 
 * 📌 WHAT IS A SCHEMA?
 * --------------------
 * Schema = Blueprint for documents in a collection
 * - Defines fields and their types
 * - Adds validation rules
 * - Sets default values
 * 
 * 📌 MONGOOSE vs RAW MONGODB:
 * ---------------------------
 * Raw MongoDB: db.threads.insertOne({anything: "goes"})
 * Mongoose: Validates data, provides methods, adds structure
 * 
 * 📌 INTERVIEW TIP:
 * -----------------
 * "I use Mongoose for schema validation and ODM features. Each Thread
 *  document contains an array of messages, making it efficient to
 *  load entire conversations in one query."
 */

import mongoose from "mongoose";
// 📖 Mongoose: ODM (Object Document Mapper) for MongoDB
// Like an ORM, but for document databases


// =============================================================================
//                         MESSAGE SUB-SCHEMA
// =============================================================================
/**
 * 📖 Embedded Schema for Individual Messages
 * ------------------------------------------
 * Each message in a thread has:
 * - role: "user" or "assistant"
 * - content: The message text
 * - timestamp: When it was sent
 * 
 * 📌 WHY EMBEDDED vs REFERENCED?
 * - Embedded: Messages stored inside Thread document
 * - Referenced: Messages in separate collection with foreign key
 * 
 * I chose Embedded because:
 * 1. Always load messages with thread (no extra query)
 * 2. Atomic updates (add message = one write)
 * 3. Good for bounded arrays (chat history)
 */

const MessageSchema = new mongoose.Schema({
    role: {
        type: String,
        enum: ["user", "assistant"],
        // 📖 enum: Only allow these values
        // 📌 Validation: Rejects "system", "bot", etc.
        required: true
    },
    content: {
        type: String,
        required: true
        // 📖 required: Cannot save without this field
    },
    timestamp: {
        type: Date,
        default: Date.now
        // 📖 default: Auto-set to current time if not provided
    }
});


// =============================================================================
//                         THREAD SCHEMA
// =============================================================================
/**
 * 📖 Main Schema for Chat Threads
 * --------------------------------
 * A Thread represents one conversation (like a ChatGPT chat).
 * 
 * Fields:
 * - threadId: UUID (unique identifier from frontend)
 * - title: Display name in sidebar (first message)
 * - messages: Array of Message subdocuments
 * - createdAt: When thread was created
 * - updatedAt: Last activity (for sorting)
 * 
 * 📌 WHY threadId vs _id?
 * - _id: MongoDB's auto-generated ObjectId
 * - threadId: UUID generated by frontend
 * 
 * Using frontend UUID allows:
 * 1. Create thread before first save
 * 2. Client knows ID immediately
 * 3. Works offline then syncs
 */

const ThreadSchema = new mongoose.Schema({
    threadId: {
        type: String,
        required: true,
        unique: true
        // 📖 unique: Creates index, prevents duplicates
        // 📌 MongoDB will reject duplicate threadId
    },
    title: {
        type: String,
        default: "New Chat"
        // 📖 Usually set to first message content
    },
    messages: [MessageSchema],
    // 📖 Array of embedded Message subdocuments
    // 📌 Accessed as: thread.messages[0].content
    
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
        // 📖 Updated manually when messages added
        // Used for sorting: most recent at top
    }
});


// =============================================================================
//                         EXPORT MODEL
// =============================================================================

export default mongoose.model("Thread", ThreadSchema);
// 📖 mongoose.model("Thread", ThreadSchema)
// - "Thread": Model name (used for collection: "threads")
// - ThreadSchema: The schema definition
// 
// 📌 USAGE:
// import Thread from "./models/Thread.js"
// const thread = new Thread({...})
// await thread.save()
// await Thread.find({})
// await Thread.findOne({threadId})


// =============================================================================
//                         SUMMARY FOR INTERVIEWS
// =============================================================================
/**
 * 📌 SCHEMA DESIGN CHOICES:
 * 
 * 1. EMBEDDED MESSAGES:
 *    - Messages stored in Thread document
 *    - One query loads entire chat
 *    - Good for bounded data (chat history)
 * 
 * 2. FRONTEND UUID (threadId):
 *    - Client generates ID
 *    - Thread exists before first save
 *    - Enables optimistic UI updates
 * 
 * 3. TIMESTAMPS:
 *    - createdAt: For analytics, sorting by age
 *    - updatedAt: For "recent chats" sorting
 * 
 * 📌 MONGOOSE FEATURES USED:
 * - Schema validation (required, enum)
 * - Default values
 * - Unique index
 * - Subdocuments (embedded schema)
 * 
 * 📌 MONGODB COLLECTION:
 * Model "Thread" → Collection "threads" (lowercased, pluralized)
 */